const CriandoSeuFotoProduto = () => (
  <>
    <h1>FotoProdutos</h1>
    <div>Antes de mais nada, convém observar que não é necessário possuir nenhum conhecimento de edição de imagens para elaborar seu FotoProduto.</div>
    <div>Muito intuitivo, nosso aplicativo online permite que você faça um bonito trabalho em poucos passos:</div>
    <br />

    <h1>Como criar um FotoLivro</h1>
    <div>O processo de criação é sempre o mesmo, para todos os nosso FotoProdutos. Para criar o seu FotoLivro personalizado é muito simples, basta seguir os passos abaixo:</div><br />
    <div><strong>1 -</strong> Clique em “FotoLivros”, no menu principal localizado no topo de nossa página principal, e escolha o modelo do FotoLivro que você deseja criar e clique em “Crie agora!” para iniciar o processo de criação.</div><br />
    <div><strong>2 -</ strong> Você será direcionado ao nosso software de criação. Para começar o seu projeto clique no botão “Adicionar”, localizado no canto superior esquerdo da tela, para abrir o menu de seleção de suas imagens.</div><br />
    <div><strong>3 -</ strong> Através do menu de exploração navegue até a pasta de seu computador em que você salvou suas imagens e escolha quais imagens você quer importar para trabalhar em seu projeto. Lembre-se que você pode selecionar mais de uma imagem ao mesmo tempo mantendo pressionada a tecla “Ctrl” e clicando nas imagens que você escolher ou, ainda, selecionar todos os arquivos de uma pasta ao mesmo tempo ao pressionar as teclas “Crtl” e “A” juntas.</div><br />
    <div><strong>4 -</ strong> Após selecionar suas imagens basta clicar em “Abrir”. Se você esquecer de alguma imagem nesta etapa, não se preocupe, você pode voltar a este ponto e selecionar mais imagens para o seu projeto a qualquer momento.</div><br />
    <div><strong>5 -</ strong> Suas imagens serão carregadas para a mesa de montagem do software de criação. Aguarde até que todas as imagens que você selecionou apareçam na parte superior da tela, para começar a trabalhar em seu projeto.</div><br />
    <div><strong>6 -</ strong> Você verá suas imagens em tamanho miniatura na barra superior da mesa, para ver sua imagens ampliada basta manter seu cursor sobre a imagem por alguns segundos. O pequeno círculo vermelho, que aparece ao passar do mouse sobre a miniatura de uma imagem, permite que você remova aquela imagem de sua mesa de trabalho. Mas atenção, para remover a imagem da mesa você terá que removê-la do seu livro, caso ela já tenha sido usada. E se após remover a imagem você mudar de ideia, será preciso selecioná-la novamente em seu computador.</div><br />
    <div><strong>7 -</ strong> Para saber qual a função de cada um dos botões da aplicação, coloque o cursor sobre qualquer botão e mantenha-o no lugar por alguns segundos para visualizar sua legenda.</div><br />
    <div><strong>8 -</ strong> Para colocar suas imagens no FotoLivro basta clicar na miniatura da imagem escolhida e arrastá-la para a página desejada. Dentro das janelas é possível movimentar a imagem para enquadrá-la no layout.</div><br />
    <div><strong>9 -</ strong> A troca dos layouts pode ser feita clicando nos botões azuis localizados abaixo de cada página, o botão da direita mostra o próximo modelo de layout e o da esquerda o anterior. São mais de 200 modelos diferentes, com várias opções de distribuição das imagens e caixas de texto nas páginas, e eles encontram-se ordenados pelo número de janelas, do menor para o maior.</div><br />
    <div><strong>10 -</ strong> Depois de inserir uma foto no livro é possível editá-la, basta passar o mouse sobre a imagem, para visualizar o menu de edição no canto superior esquerdo da foto, as opções são: +zoom, -zoom, rotacionar a imagem e remover a imagem da janela (essa opção remover é diferente da que está presente na miniatura, pois ela apenas retira a imagem da janela do livro, mantendo-a na mesa de criação).</div><br />
    <div><strong>11 -</ strong> Alguns modelos de layout possuem caixas de texto, identificadas pela frase “Digite seu texto aqui”. Para editá-las basta clicar na caixa para que o cursor apareça juntamente com as opções de edição, que oferecem diferentes opções de fonte, tamanho, alinhamento, cores etc.</div>
    <div>Caso você não tenha a intenção de usar texto em seu projeto sugerimos a escolha de outro layout, pois deixar estes espaços em branco pode causar um desequilíbrio visual em seu álbum.</div><br />
    <div><strong>12 -</ strong> Para se movimentar entre as páginas de seu FotoLivro você pode utilizar as setas de navegação, localizadas na parte inferior do livro em torno do botão azul central “Menu Livro”. Na ordem, da esquerda para a direita, você vai encontrar na esquerda a seta dupla que leva para a primeira página do livro e a seta simples que leva para a página anterior, e na direita do botão estão a seta simples que leva para a próxima página e a seta dupla que leva direto para a última página do livro. Você também pode utilizar as setas do seu teclado para realizar esta navegação, esquerda para a página anterior e direita para a próxima página.</div><br />
    <div><strong>13 -</ strong> Você pode acrescentar ou retirar páginas do seu FotoLivro através do campo que se encontra no topo da aplicação, logo abaixo do nome do produto. As páginas são acrescidas sempre em pares, devido a estrutura de montagem dos livros. Lembre-se que a inclusão de páginas extras modifica o preço inicial do produto e que todos os modelos possuem um número de páginas mínimo e máximo, consulte os detalhes de cada modelo em nossas páginas de produtos.</div><br />
    <div><strong>14 -</ strong> O botão “Menu Imagens”, localizado no canto superior esquerdo da mesa, guarda as funções referente as imagens, clique para acessar o menu. Suas funções incluem: adicionar mais imagens para a mesa, remover todas as imagens – da mesa e do livro -, agrupar imagens por diferentes critérios (todas as imagens, imagens não usadas, imagens usadas uma única vez e imagens usadas mais de uma vez) e ordenar a sequência com que as imagens são exibidas (em ordem alfabética ou por data).</div><br />
    <div><strong>15 -</ strong> Ao lado do botão “Menu Imagens” você encontra uma seta para baixo que permite que você visualize o conjunto de suas imagens espalhadas sobre a mesa de trabalho, basta clicar na seta para ativar esta visão, clique novamente na seta para voltar a visão do livro.</div><br />
    <div><strong>16 -</ strong> O botão “Menu Livro”, centralizado logo abaixo do livro, guarda todas as funções relacionadas com o livro, clique para acessar o menu. A primeira função permite que você opte por ter seu FotoLivro preenchido automaticamente pela aplicação. Atenção, as imagens serão dispostas no livro na mesma ordem em que estão na mesa e neste estágio de desenvolvimento de nosso produto, se você já tiver incluído imagens no livro e optar pelo preenchimento automático você vai perder suas alterações pois o preenchimento automático se sobrepõe a qualquer alteração já feita no projeto. A segunda função permite que você limpe seu livro retirando todas as imagens usadas até o momento e retornando-as para a mesa.</div><br />
    <div><strong>17 -</ strong> Para que você possa ter uma ideia melhor da disposição dos layouts nas páginas do seu projeto, a seta localizada sobre o botão “Menu Livro” permite que você veja todas as páginas do seu FotoLivro ao mesmo tempo. Nesta visualização você pode navegar entre as páginas utilizando as setas direcionais de seu teclado e alterar seus layouts utilizando os botões azuis “Próximo layout” e “Layout anterior”, os dois botões da esquerda controlam as páginas par e os dois da direita as páginas ímpares. Para retornar a visão do livro em página dupla basta clicar na seta novamente.</div><br />
    <div><strong>18 -</ strong> Quando você estiver feliz com o resultado do seu projeto, basta clicar no botão laranja “Pronto” localizado no canto superior direito da tela. Depois de clicar no botão você não poderá realizar mais alterações em seu projeto, seu pedido será finalizado e enviado para o nosso departamento de produção.</div>
    <div>Atenção: Nesta etapa deverá surgir em sua tela uma caixa de diálogo solicitando que você autorize que nosso sistema salve uma cópia de seu projeto em seu computador, este procedimento garante que você não perca o seu projeto caso ocorra alguma falha durante o processo de envio, como, por exemplo, no caso de uma queda de sua conexão.</div><br />
    <div><strong>19 -</ strong> Pronto! Agora é só concluir as etapas do Checkout que em poucos dias você vai receber seu lindo FotoLivro Personalizado em casa!</div><br />

  </>
);

export default CriandoSeuFotoProduto;