const FotoLivros = () => (
  <>
    <div><strong>O que é um FotoLivro</strong></div><br />
    <div>Fotos registram mais que imagens, elas registram emoções. Sabendo disso, a Printástico reuniu, em um só produto, atributos que garantirão que seus melhores momentos sejam eternizados e revisitados quando e quantas vezes você e sua família e amigos desejarem. São os FotoLivros.</div><br /><br />
    <div>FotoLivro é o nome criado pela Printástico a partir da junção das palavras FOTO e Livro, para denominar a forma moderna de customização dos álbuns de fotos tradicionais. Esses álbuns também são chamados de fotobooks, photobooks ou livros de fotos.</div><br /><br />
    <div>Partindo do tradicional conceito do álbum de fotografias, os FotoLivros vão além, permitindo inserir efeitos e detalhes nas imagens e até mesmo escolher o acabamento e os métodos de impressão. Você vai perceber que o processo de elaboração do FotoLivro é semelhante ao utilizado para a produção dos scrapbooks feitos artesanalmente usando papeis, cola e tesoura. Nesse tipo de álbum, é comum serem colados, junto às fotos, pedacinhos de papeis que ajudam a reviver o momento fotografado. Vale colar o bilhete do parque, a embalagem do presente, o folder do restaurante, entre outros. No FotoLivro também é possível inserir as mesmas imagens. Para isso basta fotografar os itens e incluí-los na seleção de fotos.</div><br /><br />
    <div>Sendo assim, você tem a oportunidade de incluir seus melhores registros fotográficos em formato digital acompanhados de textos e legendas (escritos por você mesmo!), que o ajudarão a eternizar a sua história. Dá para montar álbuns de casamento, aniversário, especiais de viagens, melhores momentos das crianças, os encontros com amigos, familiares, enfim, as possibilidades são infinitas!</div><br /><br />
    <div>A maioria de nossos álbuns pode receber a impressão de fotografias na capa e na contracapa, o que torna o seu projeto ainda mais especial. Se preferir, também disponibilizamos lindas capas em materiais diversos como couros sintéticos e tecidos em cores e texturas variadas. Os nossos FotoLivros são compostos normalmente por um mínimo de 20 páginas onde é possível inserir cerca de 20 a 40 fotos, dependendo do layout escolhido. Alguns FotoLivros podem ter até 100 páginas!</div><br /><br />
    <div>A tecnologia avançada de nossa aplicação poupa o usuário de qualquer conhecimento de ferramentas de edição de imagens, fazendo do FotoLivro o um produto simples, divertido e com garantia de final feliz. Nosso aplicativo online foi idealizado para tornar a criação de FotoLivros rápida, fácil e dinâmica. Dispomos de layouts prontos, desenvolvidos por nossa equipe de designers gráficos, que garantem praticidade e agilidade à suas produções.</div><br /><br />
    <div>Usuários que tiverem domínio de ferramentas de edição poderão enviar seus projetos, feitos em qualquer outro software, finalizados para a impressão, desde que eles estejam salvos em formato PDF. Importante: Procure as medidas exatas na descrição detalhada do produto escolhido.</div><br /><br />
    <div>Tornando eternas suas lembranças mais preciosas, os FotoLivros da Printástico são a maneira perfeita para preservar e compartilhar memórias, sendo possível guardá-las com originalidade em um material elegante e de ótimo acabamento.</div><br /><br />

    <div><strong>Escolha o formato que mais combina com você</strong></div><br />
    <div>Chegou a hora de escolher, aqui na Printástico, o formato de FotoLivro que mais lhe agrada e conferir se você tem fotos suficientes para a composição.</div><br /><br />
    <div>O primeiro passo é definir o modelo de FotoLivro que mais combina com você. Para isso, visite nossas páginas de produtos e conheça os diferentes formatos e tamanho de FotoLivros que oferecemos, no site você encontra todas as especificações de cada modelo.</div><br /><br />
    <div>A maioria dos nossos FotoLivros são elaborados com no mínimo 20 páginas e cada página pode receber, em média, até cinco imagens. Você vai encontrar estas informações, ao clicar em ‘FotoLivro’ no menu superior da página principal do site. Nossos modelos encontram-se categorizados por formatos, temos opções que variam entre os tamanhos 10x15cm até 30x45cm.</div><br /><br />
    <div>Decidiu? Então basta clicar no botão azul com a inscrição: ‘Crie agora!’ e começar a criar o seu. Nosso assistente de criação abrirá automaticamente para iniciar a montagem de seu FotoLivro.</div><br /><br />

    <div><strong>Dicas para selecionar suas imagens</strong></div><br />
    <div>O que dará valor ao seu trabalho é a sensibilidade na escolha das fotos, na disposição das imagens, bem como na inserção dos textos.</div><br /><br />
    <div>Escolhendo as fotos, disponha todas as fotos que você deseja utilizar em uma única pasta do seu computador. Isso tornará o trabalho muito mais fácil na hora de escolher as fotos.</div><br /><br />
    <div>Para facilitar ainda mais o processo de seleção das fotografias para a produção do seu FotoLivro, sugerimos o tutorial abaixo:</div><br /><br />
    <div>1. Reúna as fotos no computador: O primeiro passo é transferir as fotos que você fez – com sua câmera, aparelho celular ou tablet – para o computador. Imagens impressas também poderão ser utilizadas em seu FotoLivro, desde que sejam digitalizadas (recomendamos uma resolução mínima de 300dpi).</div><br /><br />
    <div>2. Crie uma pasta: Em seguida, agrupe, em uma pasta, as fotos que você pretende usar em seu FotoLivro. Nomeie essa pasta com o nome do seu projeto, por exemplo “AniversarioFilho”.</div><br /><br />
    <div>3. Cheque se as fotos selecionadas estão com boa resolução: Para uma boa impressão, é importante que as imagens tenham, pelo menos, 2 megapixels para o formato 10×15. Durante o processo de criação você terá uma visualização reduzida das fotografias o que pode dificultar que você note pequenos problemas de nitidez, por exemplo. Por isso vale a pena investir tempo nesta fase de preparação de todo material.</div><br /><br />
    <div>4. Corrija a orientação das fotos: Veja se elas estão alinhadas de forma correta, quer seja na horizontal ou na vertical.</div><br /><br />
    <div>5. Elabore uma sequencia: para facilitar ainda mais o trabalho, sugerimos que você organize as fotos respeitando uma sequencia logica. Se forem fotos de uma viagem, por exemplo, você pode agrupá-las por tempo (primeiro dia, segundo dia…), por grupos (com a família, com amigos), por local (na praia, no sítio…) e assim por diante conforme a sua criatividade mandar.</div><br /><br />
    <div>É interessante lembrar que os FotoLivros são compostos por quantidade de páginas e não por número de fotos. Você pode montar diversos modelos de páginas com diferentes imagens. Por isso, tenha sempre em mente o número fotos que você deseja estampar em seu fotolivro, bem como o volume de páginas pretendido para que não haja desperdício de fotografias e, muito menos, de páginas.</div><br /><br />
    <div>Pronto! agora é só colocar a mão na massa e começar a produzir o seu FotoLivro personalizado! Para adicionar suas fotos digitais à aplicação online da Printástico, basta clicar no botão laranja ‘Escolher fotos’ e selecioná-las na pasta que você criou em seu próprio computador.</div><br /><br />
  </>
);

export default FotoLivros;